routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@index')->name('index');
Route::get('/about', 'GuestController@about')->name('about');
Route::get('/blog', 'GuestController@blog')->name('blog');
Route::get('/boy-single', 'GuestController@boy')->name('boy');
Route::get('/boys', 'GuestController@boys')->name('boys');
Route::get('/checkout', 'GuestController@checkout')->name('checkout');
Route::get('/contact', 'GuestController@contact')->name('contact');
Route::get('/faq', 'GuestController@faq')->name('faq');
Route::get('/girl-single', 'GuestController@girl')->name('girl');
Route::get('/girls', 'GuestController@girls')->name('girls');
Route::get('/men-single', 'GuestController@men')->name('men');
Route::get('/mens', 'GuestController@mens')->name('mens');
Route::get('/payment', 'GuestController@payment')->name('payment');
Route::get('/shop', 'GuestController@shop')->name('shop');
Route::get('/blog-single', 'GuestController@blog_single')->name('blogs.single');
Route::get('/women-single', 'GuestController@women')->name('women');
Route::get('/womens', 'GuestController@womens')->name('womens');
Route::get('/registration', 'GuestController@registration')->name('registration');
Route::get('/u/login', 'GuestController@login')->name('user-login');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
//Route::get('photo', 'PhotoController@index')->name('photo');
//Route::post('photo', 'PhotoController@upload');

//                           UserController

Route::post('/u/login','UserController@login')->name('u.login.check');


//                         AdminUserController

Route::resource('admin-user', 'AdminUserController')->middleware('verified');


//                         AdminRoleController

Route::resource('roles','AdminRoleController')->middleware('verified');

//                       AdminDashboardController

Route::resource('dashboard','AdminDashboardController')->middleware('verified');



//                        AdminProfileController

Route::resource('profile','AdminProfileController')->middleware('verified');


//                       AdminPermissionController

Route::resource('permission','AdminPermissionController')->middleware('verified');

//                        AdminCategoryController

Route::resource('categories','AdminCategoryController')->middleware('verified');
//
//Route::GET('categories','AdminCategoryController@index')->name('categories.index');
//Route::GET('categories/create','AdminCategoryController@create')->name('categories.create');
//Route::POST('categories','AdminCategoryController@store')->name('categories.store');
//Route::GET('categories/{id}','AdminCategoryController@show')->name('categories.show');
//Route::GET('categories/{id}/edit','AdminCategoryController@edit')->name('categories.edit');
//Route::PUT('categories/{id}','AdminCategoryController@update')->name('categories.update');
//Route::DELETE('categories/{id}','AdminCategoryController@destroy')->name('categories.destroy');

//                         AdminBrandController

Route::resource('brands','AdminBrandController')->middleware('verified');

//Route::GET('brands','AdminBrandController@index')->name('brands.index');
//Route::GET('brands/create','AdminBrandController@create')->name('brands.create');
//Route::POST('brands','AdminBrandController@store')->name('brands.store');
//Route::GET('brands/{id}','AdminBrandController@show')->name('brands.show');
//Route::GET('brands/{id}/edit','AdminBrandController@edit')->name('brands.edit');
//Route::PUT('brands/{id}','AdminBrandController@update')->name('brands.update');
//Route::DELETE('brands/{id}','AdminBrandController@destroy')->name('brands.destroy');

Route::resource('products','AdminProductController')->middleware('verified');

//Route::GET('products','AdminProductController@index')->name('products.index');
//Route::GET('products/create','AdminProductController@create')->name('products.create');
//Route::POST('products','AdminProductController@store')->name('products.store');
//Route::GET('products/{id}','AdminProductController@show')->name('products.show');
//Route::GET('products/{id}/edit','AdminProductController@edit')->name('products.edit');
//Route::PUT('products/{id}','AdminProductController@update')->name('products.update');
//Route::DELETE('products/{id}','AdminProductController@destroy')->name('products.destroy');

app/Role.php
<?php

namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
}

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')

@section('head')

@endsection

@section('navbar')
    <a class="navbar-brand" id="user-b" style="display: block;" href="#" onclick="toggle_visibility('admin', 'user','user-b','admin-b');" title="View Authenticate Users table">View Authenticate Roles</a>
    <a class="navbar-brand" id="admin-b" style="display: none;" href="#" onclick="toggle_visibility('admin','user','user-b','admin-b');" title="View Customer Users table">View General Roles</a>
@endsection

@section('content')

    <div class="wrapper ">

        @include('admin.partial.sidebar')


        <div class="main-panel">
            <!-- Navbar -->
            @include('admin.partial.nav')
            <!-- End Navbar -->

            <!-- User List Table  -->

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12" id="admin" style="display: none;">
                            <div class="card">
                                <div class="card-header card-header-success">
                                    @if(session('message'))
                                        <h3 style="text-align: center; color:snow; font-weight: bold;" class="card-title">{{session('message')}}</h3>
                                    @endif
                                </div>
                                <div class="card-header card-header-primary">
                                    <div class="col-md-4 "style="float:left;">
                                        <h4 class="card-title ">Authorized User Role</h4>
                                        <p class="card-category">Authorized Users Role Table</p>
                                    </div>
                                    <div class="col-md-4" style="float:left;">
                                        <h4 class="card-title"><a  class="nav-link navbar-brand" href="{{route('roles.create')}}"  title="Create New Role">Create New Role</a></h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table" id="table_id">
                                            <thead class=" text-primary">
                                            <th>
                                                SL No
                                            </th>
                                            <th>
                                                Display Name
                                            </th>
                                            <th>
                                                Role Name
                                            </th>
                                            <th style="max-width:300px;">
                                                Description
                                            </th>
                                            <th  class="action-btn">
                                                Action
                                            </th>
                                            </thead>
                                            <tbody>
                                            <?php $i=0; ?>
                                            @foreach($authRoles as $authRole)
                                                <tr style="background:#202940;">
                                                    <td>
                                                        {{ ++$i }}
                                                    </td>
                                                    <td>
                                                        {{ $authRole->display_name }}
                                                    </td>
                                                    <td>
                                                        <span class="label success">{{ $authRole->name }}</span>
                                                    </td>
                                                    <td>
                                                        {!! $authRole->description !!}
                                                    </td>
                                                    <td class="center">
                                                        <a class="m-btn btn btn-success" href="{{route('roles.show',$authRole->id)}}">
                                                            <i class="material-icons">search</i>
                                                        </a>
                                                        <a class="m-btn btn btn-info" href="{{route('roles.edit',$authRole->id)}}">
                                                            <i class="material-icons">settings</i>
                                                        </a>
                                                        <form style="display: inline !important;" action="{{route('roles.destroy', $authRole->id)}}" method="POST">
                                                            @CSRF
                                                            @METHOD('DELETE')
                                                            <button type="submit" class="m-btn btn btn-danger" title="Delete User" onclick="return confirmDelete()">
                                                                <i class="material-icons">delete</i>
                                                            </button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12" id="user" style="display: block;">
                        <div class="card">
                            <div class="card-header card-header-success">
                                @if(session('message'))
                                    <h3 style="text-align: center; color:snow; font-weight: bold;" class="card-title">{{session('message')}}</h3>
                                @endif
                            </div>
                            <div class="card-header card-header-primary">
                                <div class="col-md-4 "style="float:left;">
                                    <h4 class="card-title ">General User Role</h4>
                                    <p class="card-category">General Users Role Table</p>
                                </div>
                                <div class="col-md-4" style="float:left;">
                                    <h4 class="card-title"><a  class="nav-link navbar-brand" href="{{route('roles.create')}}"  title="Create New Role">Create New Role</a></h4>
                                </div>
                            </div>
                            <div class="card-body"  id="table_id">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class=" text-primary">
                                        <th>
                                            SL No
                                        </th>
                                        <th>
                                            Display Name
                                        </th>
                                        <th>
                                            Role Name
                                        </th>
                                        <th style="max-width:300px;">
                                            Description
                                        </th>
                                        <th class="action-btn">
                                            Action
                                        </th>
                                        </thead>
                                        <tbody>
                                        <?php $i=0; ?>
                                        @foreach($genRoles as $genRole)
                                            <tr style="background:#202940;">
                                                <td>
                                                    {{ ++$i }}
                                                </td>
                                                <td>
                                                    {{ $genRole->display_name }}
                                                </td>
                                                <td>
                                                    <span class="label success">{{ $genRole->name }}</span>
                                                </td>
                                                <td>
                                                    {!! $genRole->description !!}
                                                </td>
                                                <td class="center">
                                                    <a class="m-btn btn btn-success" href="{{route('roles.show',$genRole->id)}}">
                                                        <i class="material-icons">search</i>
                                                    </a>
                                                    <a class="m-btn btn btn-info" href="{{route('roles.edit',$genRole->id)}}">
                                                        <i class="material-icons">settings</i>
                                                    </a>
                                                    <form style="display: inline !important;" action="{{route('roles.destroy', $genRole->id)}}" method="POST">
                                                        @CSRF
                                                        @METHOD('DELETE')
                                                    <button type="submit" class="m-btn btn btn-danger" title="Delete User" onclick="return confirmDel()">
                                                        <i class="material-icons">delete</i>
                                                    </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>


            <!--  Footer  -->

            @include('admin.partial.footer')

        </div>
    </div>

    @include('admin.partial.script')
@endsection

@section('script')

    <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
    </script>

    <script>
        function toggle_visibility(id1,id2,id3,id4) {
            let a = document.getElementById(id1);
            let u = document.getElementById(id2);
            let ab = document.getElementById(id3);
            let ub = document.getElementById(id4);
            a.style.display = ((a.style.display!=='none') ? 'none' : 'block');
            u.style.display = ((u.style.display!=='none') ? 'none' : 'block');
            ab.style.display = ((ab.style.display!=='none') ? 'none' : 'block');
            ub.style.display = ((ub.style.display!=='none') ? 'none' : 'block');
        }

        function confirmDel() {
            let del = confirm('Are you sure to delete this Role?');
            if(del)
                return true;
            else
                return false;
        }
    </script>

@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.admin')

@section('head')

@endsection

@section('navbar')
    <!-- <a class="navbar-brand" id="user-b" style="display: block;" href="#" onclick="toggle_visibility('admin', 'user','user-b','admin-b');" title="View Authenticate Users table">View Authenticate Users</a>
    <a class="navbar-brand" id="admin-b" style="display: none;" href="#" onclick="toggle_visibility('admin','user','user-b','admin-b');" title="View Customer Users table">View Customer Users</a> -->
@endsection

@section('content')

    <div class="wrapper ">

        @include('admin.partial.sidebar')


        <div class="main-panel">
            <!-- Navbar -->
        @include('admin.partial.nav')
        <!-- End Navbar -->

            <!-- User List Table  -->

            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header card-header-primary">
                                    <div class="col-md-4 "style="float:left;">
                                        <h4 class="card-title ">Role</h4>
                                        <p class="card-category">Roles Table</p>
                                    </div>
                                    <div class="col-md-4" style="float:left;">
                                        <h4 class="card-title"><a  class="nav-link navbar-brand" href="{{route('roles.create')}}"  title="Create New Role">Create New Role</a></h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead class=" text-primary">
                                            <th>
                                                ID No
                                            </th>
                                            <th>
                                                Display Name
                                            </th>
                                            <th>
                                                Role Name
                                            </th>
                                            <th>
                                                Description
                                            </th>
                                            <th class="action-btn">
                                                Action
                                            </th>
                                            </thead>
                                            <tbody>
                                            <tr style="background:#202940;">
                                                <td>
                                                    {{ $roles->id }}
                                                </td>
                                                <td>
                                                    {{ $roles->display_name }}
                                                </td>
                                                <td>
                                                    <span class="btn">{{ $roles->name }}</span>
                                                </td>
                                                <td>
                                                    {!! $roles->description !!}
                                                </td>
                                                <td class="center">
                                                    <a class="btn btn-success" href="{{route('roles.show',$roles->id)}}">
                                                        <i class="material-icons">search</i>
                                                    </a>
                                                    <a class="btn btn-info" href="{{route('roles.edit',$roles->id)}}">
                                                        <i class="material-icons">settings</i>
                                                    </a>
                                                    <form style="display: inline !important;" action="{{route('roles.destroy', $roles->id)}}" method="POST">
                                                        @CSRF
                                                        @METHOD('PUT')
                                                        <button type="submit" class="btn btn-danger" title="Delete User" onclick="return confirmDelete()">
                                                            <i class="material-icons">delete</i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--  Footer  -->

        @include('admin.partial.footer')

    </div>
    </div>

@endsection

@section('script')

    <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
    </script>

    <script>
        function toggle_visibility(id1,id2,id3,id4) {
            let a = document.getElementById(id1);
            let u = document.getElementById(id2);
            let ab = document.getElementById(id3);
            let ub = document.getElementById(id4);
            a.style.display = ((a.style.display!=='none') ? 'none' : 'block');
            u.style.display = ((u.style.display!=='none') ? 'none' : 'block');
            ab.style.display = ((ab.style.display!=='none') ? 'none' : 'block');
            ub.style.display = ((ub.style.display!=='none') ? 'none' : 'block');
        }

        function confirmDelete(){
            let del = confirm('Are You Sure to Delete this Role?');
            if(del)
                return true;
            else
                return false;
        }
    </script>

@endsection