routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@index')->name('index');
Route::get('/about', 'GuestController@about')->name('about');
Route::get('/blog', 'GuestController@blog')->name('blog');
Route::get('/boy-single', 'GuestController@boy')->name('boy');
Route::get('/boys', 'GuestController@boys')->name('boys');
Route::get('/checkout', 'GuestController@checkout')->name('checkout');
Route::get('/contact', 'GuestController@contact')->name('contact');
Route::get('/faq', 'GuestController@faq')->name('faq');
Route::get('/girl-single', 'GuestController@girl')->name('girl');
Route::get('/girls', 'GuestController@girls')->name('girls');
Route::get('/men-single', 'GuestController@men')->name('men');
Route::get('/mens', 'GuestController@mens')->name('mens');
Route::get('/payment', 'GuestController@payment')->name('payment');
Route::get('/shop', 'GuestController@shop')->name('shop');
Route::get('/blog-single', 'GuestController@blog_single')->name('blogs.single');
Route::get('/women-single', 'GuestController@women')->name('women');
Route::get('/womens', 'GuestController@womens')->name('womens');
Route::get('/registration', 'GuestController@registration')->name('registration');
Route::get('/u/login', 'GuestController@login')->name('user-login');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
//Route::get('photo', 'PhotoController@index')->name('photo');
//Route::post('photo', 'PhotoController@upload');

//                           UserController

Route::post('/u/login','UserController@login')->name('u.login.check');


//                         AdminUserController

Route::resource('admin-user', 'AdminUserController')->middleware('verified');


//                         AdminRoleController

Route::resource('roles','AdminRoleController')->middleware('verified');

//                       AdminDashboardController

Route::resource('dashboard','AdminDashboardController')->middleware('verified');



//                        AdminProfileController

Route::resource('profile','AdminProfileController')->middleware('verified');


//                       AdminPermissionController

Route::resource('permission','AdminPermissionController')->middleware('verified');

//                        AdminCategoryController

Route::resource('categories','AdminCategoryController')->middleware('verified');
//
//Route::GET('categories','AdminCategoryController@index')->name('categories.index');
//Route::GET('categories/create','AdminCategoryController@create')->name('categories.create');
//Route::POST('categories','AdminCategoryController@store')->name('categories.store');
//Route::GET('categories/{id}','AdminCategoryController@show')->name('categories.show');
//Route::GET('categories/{id}/edit','AdminCategoryController@edit')->name('categories.edit');
//Route::PUT('categories/{id}','AdminCategoryController@update')->name('categories.update');
//Route::DELETE('categories/{id}','AdminCategoryController@destroy')->name('categories.destroy');

//                         AdminBrandController

Route::resource('brands','AdminBrandController')->middleware('verified');

//Route::GET('brands','AdminBrandController@index')->name('brands.index');
//Route::GET('brands/create','AdminBrandController@create')->name('brands.create');
//Route::POST('brands','AdminBrandController@store')->name('brands.store');
//Route::GET('brands/{id}','AdminBrandController@show')->name('brands.show');
//Route::GET('brands/{id}/edit','AdminBrandController@edit')->name('brands.edit');
//Route::PUT('brands/{id}','AdminBrandController@update')->name('brands.update');
//Route::DELETE('brands/{id}','AdminBrandController@destroy')->name('brands.destroy');

Route::resource('products','AdminProductController')->middleware('verified');

//Route::GET('products','AdminProductController@index')->name('products.index');
//Route::GET('products/create','AdminProductController@create')->name('products.create');
//Route::POST('products','AdminProductController@store')->name('products.store');
//Route::GET('products/{id}','AdminProductController@show')->name('products.show');
//Route::GET('products/{id}/edit','AdminProductController@edit')->name('products.edit');
//Route::PUT('products/{id}','AdminProductController@update')->name('products.update');
//Route::DELETE('products/{id}','AdminProductController@destroy')->name('products.destroy');

resources/views/partial/construct/footer.blade.php
<footer>
    <div class="footerv2-w3ls">
        <div class="footer-w3lagile-innerr">
            <!-- footer-top -->
            <div class="container-fluid">
                <div class="row  footer-v2grids w3-agileits">
                    <!-- services -->
                    <div class="col-lg-2 col-sm-6 footer-v2grid">
                        <h4>Support</h4>
                        <ul>

                            <li>
                                <a href="{{route('payment')}}">Payment</a>
                            </li>
                            <li>
                                <a href="#">Shipping</a>
                            </li>
                            <li>
                                <a href="#">Cancellation & Returns</a>
                            </li>
                            <li>
                                <a href="{{route('faq')}}">FAQ</a>
                            </li>
                        </ul>
                    </div>
                    <!-- //services -->
                    <!-- latest posts -->
                    <div class="col-lg-3 col-sm-6 footer-v2grid mt-sm-0 mt-5">
                        <h4>Latest Blog</h4>
                        <div class="footer-v2grid1 row">
                            <div class="col-4 footer-v2grid1-left">
                                <a href="blog.html">
                                    <img src="{{asset('frontend/images/bl2.jpg')}}" alt=" " class="img-fluid">
                                </a>
                            </div>
                            <div class="col-8 footer-v2grid1-right p-0">
                                <a href="blog.html">eveniie arcet ut moles morbi dapiti</a>
                            </div>
                        </div>
                        <div class="footer-v2grid1 row my-2">
                            <div class="col-4 footer-v2grid1-left">
                                <a href="blog.html">
                                    <img src="{{asset('frontend/images/bl1.jpg')}}" alt=" " class="img-fluid">
                                </a>
                            </div>
                            <div class="col-8 footer-v2grid1-right p-0">
                                <a href="blog.html">earum rerum tenmorbi dapiti et</a>
                            </div>
                        </div>
                        <div class="footer-v2grid1 row">
                            <div class="col-4 footer-v2grid1-left">
                                <a href="blog.html">
                                    <img src="{{asset('frontend/images/bl3.jpg')}}" alt=" " class="img-fluid">
                                </a>
                            </div>
                            <div class="col-8 footer-v2grid1-right p-0">
                                <a href="blog.html">morbi dapiti eveniet ut molesti</a>
                            </div>
                        </div>
                    </div>
                    <!-- //latest posts -->
                    <!-- locations -->
                    <div class="col-lg-2 col-sm-6 footer-v2grid my-lg-0 my-5">
                        <h4>office locations</h4>
                        <ul>
                            <li>
                                <a href="#">new jersey</a>
                            </li>
                            <li>
                                <a href="#">texas</a>
                            </li>
                            <li>
                                <a href="#">michigan</a>
                            </li>
                            <li>
                                <a href="#">cannada</a>
                            </li>
                            <li>
                                <a href="#">brazil</a>
                            </li>
                            <li>
                                <a href="#">california</a>
                            </li>
                        </ul>
                    </div>
                    <!-- //locations -->
                    <!-- flickr posts -->
                    <div class="col-lg-3 col-sm-6 footer-v2grid my-lg-0 my-sm-5">
                        <h4 class="b-lo')}}">
                            flickr posts
                        </h4>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl4.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl1.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl6.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl5.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>

                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl2.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl3.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl6.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl4.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                        <div class="footer-v2grid-instagram">
                            <a href="#">
                                <img src="{{asset('frontend/images/bl5.jpg')}}" alt=" " class="img-fluid">
                            </a>
                        </div>
                    </div>
                    <!-- //flickr posts -->
                    <!-- popular tags -->
                    <div class="col-lg-2  footer-v2grid mt-sm-0 mt-5">
                        <h4>popular tags</h4>
                        <ul class="w3-tag2">
                            <li>
                                <a href="shop.html">amet</a>
                            </li>
                            <li>
                                <a href="men.html">placerat</a>
                            </li>
                            <li>
                                <a href="shop.html">Proin </a>
                            </li>
                            <li>
                                <a href="boys.html">vehicula</a>
                            </li>
                            <li>
                                <a href="shop.html">diam</a>
                            </li>
                            <li>
                                <a href="women.html">velit</a>
                            </li>
                            <li>
                                <a href="shop.html">felis</a>
                            </li>
                            <li>
                                <a href="shop.html">mauris</a>
                            </li>
                            <li>
                                <a href="girls.html">amet</a>
                            </li>
                            <li>
                                <a href="shop.html">placerat</a>
                            </li>
                            <li>
                                <a href="shop.html">Proin </a>
                            </li>
                            <li>
                                <a href="index.html">vehicula</a>
                            </li>
                            <li>
                                <a href="shop.html">diam</a>
                            </li>
                            <li>
                                <a href="men.html">velit</a>
                            </li>
                            <li>
                                <a href="shop.html">felis</a>
                            </li>
                            <li>
                                <a href="women.html">mauris</a>
                            </li>
                        </ul>
                    </div>
                    <!-- //popular tags -->
                </div>
            </div>
            <!-- //footer-top -->
            <div class="footer-bottomv2 py-5">
                <div class="container">
                    <ul class="bottom-links-agile">
                        <li>
                            <a href="{{route('index')}}">Home</a>
                        </li>
                        <li>
                            <a href="{{route('about')}}">About Us</a>
                        </li>
                        <li>
                            <a href="{{route('shop')}}">Shop</a>
                        </li>
                        <li>
                            <a href="{{route('contact')}}">Contact</a>
                        </li>

                    </ul>
                    <h3 class="text-center follow">Follow Us</h3>
                    <ul class="social-iconsv2 agileinfo">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid py-5 footer-copy_w3ls">
            <div class="d-lg-flex justify-content-between">
                <div class="mt-2 sub-some align-self-lg-center">
                    <h5>Payment Method</h5>
                    <ul class="mt-4">
                        <li class="list-inline-item">
                            <img src="{{asset('frontend/images/pay2.png')}}" alt="">
                        </li>
                        <li class="list-inline-item">
                            <img src="{{asset('frontend/images/pay5.png')}}" alt="">
                        </li>
                        <li class="list-inline-item">
                            <img src="{{asset('frontend/images/pay3.png')}}" alt="">
                        </li>
                        <li class="list-inline-item">
                            <img src="{{asset('frontend/images/pay7.png')}}" alt="">
                        </li>
                        <li class="list-inline-item">
                            <img src="{{asset('frontend/images/pay8.png')}}" alt="">
                        </li>
                        <li class="list-inline-item ">
                            <img src="{{asset('frontend/images/pay9.png')}}" alt="">
                        </li>
                    </ul>
                </div>
                <div class="cpy-right align-self-center">
                    <h2 class="agile_btxt">
                        <a href="{{route('index')}}">
                            <span>f</span>ashion
                            <span>h</span>ub</a>
                    </h2>
                    <p>© 2018 Fashion Hub. All rights reserved | Design by
                        <a href="http://w3layouts.com" class="text-secondary"> W3layouts.</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/partial/construct/head.blade.php
<head>
    <title>Fashion Hub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8" />
    <meta name="keywords" content="Fashion Hub Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="{{asset('frontend/css/bootstrap.css')}}" type="text/css" rel="stylesheet" media="all">
    <link href="{{asset('frontend/css/flexslider.css')}}" type="text/css" rel="stylesheet" media="all">

    <!-- shop css -->
    <link href="{{asset('frontend/css/shop.css')}}" type="text/css" rel="stylesheet" media="all">

    <!-- Range-slider-css -->
    <link rel="stylesheet" type="text/css" href="{{asset('frontend/css/jquery-ui1.css')}}">
    <!-- Owl-Carousel-CSS -->
    <link rel="stylesheet" href="{{asset('frontend/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('frontend/css/owl.carousel.min.css')}}" type="text/css" media="all">
    <!-- Owl Stylesheets -->
    <!-- <link rel="stylesheet" href="{{asset('frontend/css/owl.theme.default.min.css')}}"> -->
    <!-- Style-CSS -->
    <link href="{{asset('frontend/css/style.css')}}" type="text/css" rel="stylesheet" media="all">
    <!-- font-awesome icons -->
    <link href="{{asset('frontend/css/fontawesome-all.min.css')}}" rel="stylesheet">

    <!-- //Custom Theme files -->
    <!-- online-fonts -->
    <link href="//fonts.googleapis.com/css?family=Elsie+Swash+Caps:400,900" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
    <!-- //online-fonts -->

    @yield('head')

</head>

resources/views/partial/construct/modal.blade.php
{{--<!-- sign up Modal -->--}}
{{--<div class="modal fade" id="myModal_btn" tabindex="-1" role="dialog" aria-labelledby="myModal_btn" aria-hidden="true">--}}
    {{--<div class="agilemodal-dialog modal-dialog" role="document">--}}
        {{--<div class="modal-content">--}}
            {{--<div class="modal-header">--}}
                {{--<h5 class="modal-title">Register Now</h5>--}}
                {{--<button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
                    {{--<span aria-hidden="true">×</span>--}}
                {{--</button>--}}
            {{--</div>--}}
            {{--<div class="modal-body pt-3 pb-5 px-sm-5">--}}
                {{--<div class="row">--}}
                    {{--<div class="col-md-6 mx-auto align-self-center">--}}
                        {{--<img src="{{asset('frontend/images/p3.png')}}" class="img-fluid" alt="login_image" />--}}
                    {{--</div>--}}
                    {{--<div class="col-md-6">--}}
                        {{--<form action="{{route('user.store')}}" method="POST">--}}
                            {{--@if ($errors->any())--}}
                                {{--<div class="alert alert-danger">--}}
                                    {{--<ul>--}}
                                        {{--@foreach ($errors->all() as $error)--}}
                                            {{--<li>{{ $error }}</li>--}}
                                        {{--@endforeach--}}
                                    {{--</ul>--}}
                                {{--</div>--}}
                            {{--@endif--}}
                            {{--@CSRF--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="recipient-name1" class="col-form-label">Your Name</label>--}}
                                {{--<input type="text" class="form-control {{ $errors->has('first_name') ? ' is-invalid' : '' }}" placeholder=" " name="first_name" id="recipient-name1" value="{{old('first_name')}}"  required>--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="recipient-name1" class="col-form-label">User Name</label>--}}
                                {{--<input type="text" class="form-control {{ $errors->has('username') ? ' is-invalid' : '' }}" placeholder=" " name="username" id="recipient-name1" value="{{old('username')}}"  required>--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="recipient-email" class="col-form-label">Email</label>--}}
                                {{--<input type="email" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{old('email')}}"id="recipient-email"  required autofocus >--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="password1" class="col-form-label">Password</label>--}}
                                {{--<input type="password" class="form-control {{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" id="password1" required>--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="password2" class="col-form-label">Confirm Password</label>--}}
                                {{--<input type="password" class="form-control" placeholder=" " name="password_confirmation" id="password2" required>--}}
                            {{--</div>--}}
                            {{--<div class="sub-w3l">--}}
                                {{--<div class="sub-agile">--}}
                                    {{--<input type="checkbox" id="brand2" value="">--}}
                                    {{--<label for="brand2" class="mb-3">--}}
                                        {{--<span></span>I Accept to the Terms & Conditions</label>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="right-w3l">--}}
                                {{--<input type="submit" class="form-control" value="Register">--}}
                            {{--</div>--}}
                        {{--</form>--}}
                        {{--<p class="text-center mt-3">Already a member?--}}
                            {{--<a href="#" data-toggle="modal" data-target="#exampleModal1" class="text-dark login_btn">--}}
                                {{--Login Now</a>--}}
                        {{--</p>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</div>--}}
{{--<!-- //signup modal -->--}}
{{--<!-- signin Modal -->--}}
{{--<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModal1" aria-hidden="true">--}}
    {{--<div class="agilemodal-dialog modal-dialog" role="document">--}}
        {{--<div class="modal-content">--}}
            {{--<div class="modal-header">--}}
                {{--<h5 class="modal-title" id="exampleModalLabel">Login</h5>--}}
                {{--<button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
                    {{--<span aria-hidden="true">×</span>--}}
                {{--</button>--}}
            {{--</div>--}}
            {{--<div class="modal-body  pt-3 pb-5 px-sm-5">--}}
                {{--<div class="row">--}}
                    {{--<div class="col-md-6 align-self-center">--}}
                        {{--<img src="{{asset('frontend/images/p3.png')}}" class="img-fluid" alt="login_image" />--}}
                    {{--</div>--}}
                    {{--<div class="col-md-6">--}}
                        {{--<form action="{{route('login')}}" method="post">--}}
                            {{--@csrf--}}
                            {{--<div class="form-group">--}}
                                {{--<label for="recipient-name" class="col-form-label">{{ __('Email Address') }}</label>--}}
                                {{--<input type="email" class="form-control {{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder=" " name="email" id="recipient-email" value="{{ old('email') }}" required autofocus>--}}
                                {{--@if ($errors->has('email'))--}}
                                    {{--<span class="invalid-feedback" role="alert">--}}
                                        {{--<strong>{{ $errors->first('email') }}</strong>--}}
                                    {{--</span>--}}
                                {{--@endif--}}
                            {{--</div>--}}
                            {{--<div class="form-group">--}}
                                {{--<label class="col-form-label">{{ __('Password') }}</label>--}}
                                {{--<input type="password" class="form-control {{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder=" " name="password" required>--}}
                                {{--@if ($errors->has('password'))--}}
                                    {{--<span class="invalid-feedback" role="alert">--}}
                                        {{--<strong>{{ $errors->first('password') }}</strong>--}}
                                    {{--</span>--}}
                                {{--@endif--}}
                            {{--</div>--}}
                            {{--<div class="form-group row">--}}
                                {{--<div class="col-md-12 offset-md-3">--}}
                                    {{--<div class="form-check">--}}
                                        {{--<input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>--}}

                                        {{--<label class="form-check-label" for="remember">--}}
                                            {{--{{ __('Remember Me') }}--}}
                                        {{--</label>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                            {{--<div class="form-group row mb-0">--}}
                                {{--<div class="col-md-12 offset-md-1">--}}
                                    {{--<button type="submit" class="btn btn-primary">--}}
                                        {{--{{ __('Login') }}--}}
                                    {{--</button>--}}

                                    {{--<a class="btn btn-link" href="{{ route('password.request') }}">--}}
                                        {{--{{ __('Forgot Your Password?') }}--}}
                                    {{--</a>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                        {{--</form>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
{{--</div>--}}
{{--<!-- signin Modal -->--}}