routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@index')->name('index');
Route::get('/about', 'GuestController@about')->name('about');
Route::get('/blog', 'GuestController@blog')->name('blog');
Route::get('/boy-single', 'GuestController@boy')->name('boy');
Route::get('/boys', 'GuestController@boys')->name('boys');
Route::get('/checkout', 'GuestController@checkout')->name('checkout');
Route::get('/contact', 'GuestController@contact')->name('contact');
Route::get('/faq', 'GuestController@faq')->name('faq');
Route::get('/girl-single', 'GuestController@girl')->name('girl');
Route::get('/girls', 'GuestController@girls')->name('girls');
Route::get('/men-single', 'GuestController@men')->name('men');
Route::get('/mens', 'GuestController@mens')->name('mens');
Route::get('/payment', 'GuestController@payment')->name('payment');
Route::get('/shop', 'GuestController@shop')->name('shop');
Route::get('/blog-single', 'GuestController@blog_single')->name('blogs.single');
Route::get('/women-single', 'GuestController@women')->name('women');
Route::get('/womens', 'GuestController@womens')->name('womens');
Route::get('/registration', 'GuestController@registration')->name('registration');
Route::get('/u/login', 'GuestController@login')->name('user-login');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');
//Route::get('photo', 'PhotoController@index')->name('photo');
//Route::post('photo', 'PhotoController@upload');

//                           UserController

Route::post('/u/login','UserController@login')->name('u.login.check');


//                         AdminUserController

Route::resource('admin-user', 'AdminUserController')->middleware('verified');


//                         AdminRoleController

Route::resource('roles','AdminRoleController')->middleware('verified');

//                       AdminDashboardController

Route::resource('dashboard','AdminDashboardController')->middleware('verified');



//                        AdminProfileController

Route::resource('profile','AdminProfileController')->middleware('verified');


//                       AdminPermissionController

Route::resource('permission','AdminPermissionController')->middleware('verified');

//                        AdminCategoryController

Route::resource('categories','AdminCategoryController')->middleware('verified');
//
//Route::GET('categories','AdminCategoryController@index')->name('categories.index');
//Route::GET('categories/create','AdminCategoryController@create')->name('categories.create');
//Route::POST('categories','AdminCategoryController@store')->name('categories.store');
//Route::GET('categories/{id}','AdminCategoryController@show')->name('categories.show');
//Route::GET('categories/{id}/edit','AdminCategoryController@edit')->name('categories.edit');
//Route::PUT('categories/{id}','AdminCategoryController@update')->name('categories.update');
//Route::DELETE('categories/{id}','AdminCategoryController@destroy')->name('categories.destroy');

//                         AdminBrandController

Route::resource('brands','AdminBrandController')->middleware('verified');

//Route::GET('brands','AdminBrandController@index')->name('brands.index');
//Route::GET('brands/create','AdminBrandController@create')->name('brands.create');
//Route::POST('brands','AdminBrandController@store')->name('brands.store');
//Route::GET('brands/{id}','AdminBrandController@show')->name('brands.show');
//Route::GET('brands/{id}/edit','AdminBrandController@edit')->name('brands.edit');
//Route::PUT('brands/{id}','AdminBrandController@update')->name('brands.update');
//Route::DELETE('brands/{id}','AdminBrandController@destroy')->name('brands.destroy');

Route::resource('products','AdminProductController')->middleware('verified');

//Route::GET('products','AdminProductController@index')->name('products.index');
//Route::GET('products/create','AdminProductController@create')->name('products.create');
//Route::POST('products','AdminProductController@store')->name('products.store');
//Route::GET('products/{id}','AdminProductController@show')->name('products.show');
//Route::GET('products/{id}/edit','AdminProductController@edit')->name('products.edit');
//Route::PUT('products/{id}','AdminProductController@update')->name('products.update');
//Route::DELETE('products/{id}','AdminProductController@destroy')->name('products.destroy');

resources/views/admin/partial/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="float-left">
            <ul>
                <li>
                    <a href="https://www.creative-tim.com">
                        Creative Tim
                    </a>
                </li>
                <li>
                    <a href="https://creative-tim.com/presentation">
                        About Us
                    </a>
                </li>
                <li>
                    <a href="http://blog.creative-tim.com">
                        Blog
                    </a>
                </li>
                <li>
                    <a href="https://www.creative-tim.com/license">
                        Licenses
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright float-right" id="date">
            , made with <i class="material-icons">favorite</i> by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
        </div>
    </div>
</footer>

resources/views/admin/partial/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            @yield('navbar')
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="submit" class="btn btn-default btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)">
                        <i class="material-icons">dashboard</i>
                        <p class="d-lg-none d-md-block">
                            Stats
                        </p>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javscript:void(0)" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="javascript:void(0)">Mike John responded to your email</a>
                        <a class="dropdown-item" href="javascript:void(0)">You have 5 new tasks</a>
                        <a class="dropdown-item" href="javascript:void(0)">You're now friend with Andrew</a>
                        <a class="dropdown-item" href="javascript:void(0)">Another Notification</a>
                        <a class="dropdown-item" href="javascript:void(0)">Another One</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:void(0)" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        {{ Auth::user()->username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{{route('profile.index')}}">Profile</a>
                        <a  class="dropdown-item" href="{{route('admin-user.index')}}">Setting</a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/partial/plugin.blade.php
{{--<!-- It's Optional... If not Need, Do not use -->--}}

{{--<div class="fixed-plugin">--}}
    {{--<div class="dropdown show-dropdown">--}}
        {{--<a href="#" data-toggle="dropdown">--}}
            {{--<i class="fa fa-cog fa-2x"> </i>--}}
        {{--</a>--}}
        {{--<ul class="dropdown-menu">--}}
            {{--<li class="header-title"> Sidebar Filters</li>--}}
            {{--<li class="adjustments-line">--}}
                {{--<a href="javascript:void(0)" class="switch-trigger active-color">--}}
                    {{--<div class="badge-colors ml-auto mr-auto">--}}
                        {{--<span class="badge filter badge-purple active" data-color="purple"></span>--}}
                        {{--<span class="badge filter badge-azure" data-color="azure"></span>--}}
                        {{--<span class="badge filter badge-green" data-color="green"></span>--}}
                        {{--<span class="badge filter badge-warning" data-color="orange"></span>--}}
                        {{--<span class="badge filter badge-danger" data-color="danger"></span>--}}
                    {{--</div>--}}
                    {{--<div class="clearfix"></div>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="header-title">Images</li>--}}
            {{--<li>--}}
                {{--<a class="img-holder switch-trigger" href="javascript:void(0)">--}}
                    {{--<img src="{{asset('assets/img/sidebar-1.jpg')}}" alt="">--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="active">--}}
                {{--<a class="img-holder switch-trigger" href="javascript:void(0)">--}}
                    {{--<img src="{{asset('assets/img/sidebar-2.jpg')}}" alt="">--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a class="img-holder switch-trigger" href="javascript:void(0)">--}}
                    {{--<img src="{{asset('assets/img/sidebar-3.jpg')}}" alt="">--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a class="img-holder switch-trigger" href="javascript:void(0)">--}}
                    {{--<img src="{{asset('assets/img/sidebar-4.jpg')}}" alt="">--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="button-container">--}}
                {{--<a href="https://www.creative-tim.com/product/material-dashboard-dark" target="_blank" class="btn btn-primary btn-block">Free Download</a>--}}
            {{--</li>--}}
            {{--<!-- <li class="header-title">Want more components?</li>--}}
                {{--<li class="button-container">--}}
                    {{--<a href="https://www.creative-tim.com/product/material-dashboard-pro" target="_blank" class="btn btn-warning btn-block">--}}
                      {{--Get the pro version--}}
                    {{--</a>--}}
                {{--</li> -->--}}
            {{--<li class="button-container">--}}
                {{--<a href="https://demos.creative-tim.com/material-dashboard-dark/docs/2.0/getting-started/introduction.html" target="_blank" class="btn btn-default btn-block">--}}
                    {{--View Documentation--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="button-container github-star">--}}
                {{--<a class="github-button" href="https://github.com/creativetimofficial/material-dashboard/tree/dark-edition" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star ntkme/github-buttons on GitHub">Star</a>--}}
            {{--</li>--}}
            {{--<li class="header-title">Thank you for 95 shares!</li>--}}
            {{--<li class="button-container text-center">--}}
                {{--<button id="twitter" class="btn btn-round btn-twitter"><i class="fa fa-twitter"></i> &middot; 45</button>--}}
                {{--<button id="facebook" class="btn btn-round btn-facebook"><i class="fa fa-facebook-f"></i> &middot; 50</button>--}}
                {{--<br>--}}
                {{--<br>--}}
            {{--</li>--}}
        {{--</ul>--}}
    {{--</div>--}}
{{--</div>--}}

resources/views/admin/partial/script.blade.php
<script>


</script>

resources/views/admin/partial/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="black" data-image="../assets/img/sidebar-2.jpg">
    <!--
              Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

              Tip 2: you can also add an image using data-image tag
          -->
    <div class="logo">
        <a href="#" class="simple-text logo-normal">
            Creative Tim
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item active  ">
                <a class="nav-link" href="{{route('dashboard.index')}}">
                    <i class="material-icons">dashboard</i>
                    <p>{{ __('Dashboard') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{route('admin-user.index')}}">
                    <i class="material-icons">group</i>
                    <p>{{ __('Users') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{route('roles.index')}}">
                    <i class="material-icons">people_outline</i>
                    <p>{{ __('Designation (Role)') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{route('permission.index')}}">
                    <i class="material-icons">content_paste</i>
                    <p>{{ __('Permission List') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{route('categories.index')}}">
                    <i class="material-icons">library_books</i>
                    <p>{{ __('Category') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{route('brands.index')}}">
                    <i class="material-icons">library_books</i>
                    <p>{{ __('Brands') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{route('products.index')}}">
                    <i class="material-icons">library_books</i>
                    <p>{{ __('Products') }}</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="./icons.html">
                    <i class="material-icons">bubble_chart</i>
                    <p>Icons</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="./map.html">
                    <i class="material-icons">location_ons</i>
                    <p>Maps</p>
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="./notifications.html">
                    <i class="material-icons">notifications</i>
                    <p>Notifications</p>
                </a>
            </li>
             {{--<li class="nav-item active-pro ">--}}
                  {{--<a class="nav-link" href="./upgrade.html">--}}
                      {{--<i class="material-icons">unarchive</i>--}}
                      {{--<p>Upgrade to PRO</p>--}}
                  {{--</a>--}}
              {{--</li>--}}
        </ul>
    </div>
</div>